### ISSUE TITLE
Allow input for format to accept whole document and extract sentences

### ISSUE THREAD

**Issue by PhaniJella** [JingL1014/Phrase_extractor#1]
The input format at present is sentence by sentence. We want to input whole document and let the parser split the document into sentences and process it.

**Comment by JingL1014** [comment]
what will be the format of whole document? is it just a .txt file or a .xml file? Could you provide a sample document?

**Comment by PhaniJella** [comment]
We have documents stored in Mongodb. You can consider them as simple Arabic text documents containing paragraphs.

**Comment by JingL1014** [comment]
i don't think i have the access to your database. Could you attach several documents here? Thanks

**Comment by PhaniJella** [comment]
Here is the sample XML file text in Word. Cannot upload direct XML here so pasted the content of XML to word document
[Sample_Arabic.docx](https://github.com/JingL1014/Phrase_extractor/files/463220/Sample_Arabic.docx)

**Comment by JingL1014** [comment]
i tried different methods. And there are 2 options right now. The first method is simply using regular expression to do sentence splitting. The regular expression encodes the sentence boundary, e,g we can use this one [.]|[!?]+|[!\u061F]+. It could handle most cases, but it cannot handle some complicated case, e.g. abbreviation word U.S. will be split into two sentences. I am not sure if this is a problem for Arabic. And the other method is using Stanford CoreNLP. But sentence splitting in CoreNLP is not implemented in python NLTK package. We can do sentence splitting as preprocessing step though the command line. But CoreNLP process document by document, it will generate one output for each document so there will be a lot of intermediate files. Which method do you think is better?

**Comment by JingL1014** [comment]
I have update the code to allow document as input format. I finally decided to use Stanford CoreNLP to do sentence splitting.

**Comment by PhaniJella** [comment]
Thank you. Can you help me out with Turbo parser issue I mentioned previously.
